### PR TITLE
REP-33: transition to Review

### PR DESCRIPTION
**Pull request by kallydev**

### CODE REVIEW

**Review by iavl — DISMISSED** [review]

**Comment by HenryQW** [comment]
I think we have not agreed on the grace period for a Node to transit into exited.

https://forum.rss3.io/t/rep-33-node-state-transition/173/2?u=henry

**Review by HenryQW — CHANGES_REQUESTED** [review]
I think we have not agreed on the grace period for a Node to transit into exited.

https://forum.rss3.io/t/rep-33-node-state-transition/173/2?u=henry

**Review by brucexc — APPROVED** [review]

**Comment by HenryQW** [comment]
More discussions are needed to move this forward, they are many unsolved problems: https://forum.rss3.io/t/rep-33-node-state-transition/173/8

**Comment by HenryQW** [comment]
closed in favor of #46

**Pull request closed without merging**
